dependencies:
  - smartcontractkit/chainlink-brownie-contracts@1.1.1
  - OpenZeppelin/openzeppelin-contracts@4.3.0
compiler:
  solc:
    remappings:
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1'
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.3.0'
networks:
  default: development
  sepolia:
    pricefeed: '0x694AA1769357215DE4FAC081bf1f309aDC325306'
    verify: True
  development:
    verify: False
  ganache-local:
    verify: False
  mainnet-fork:
    pricefeed: '0x694AA1769357215DE4FAC081bf1f309aDC325306'
    verify: False
wallets:
  from_key: ${PRIVATE_KEY}